### ISSUE TITLE
Cyber Garage Maven Repository unavailable

### ISSUE THREAD

**Issue by ReeganExE** [cybergarage/cybergarage-upnp#28]
Hi,

I try to access the Cyber Garage Maven Repository, but it' unavailable now.

![image](https://user-images.githubusercontent.com/7277418/67261088-3a95a400-f4c9-11e9-87a7-4c1788a18173.png)

Could you please help?

**Comment by cybergarage** [comment]
@ReeganExE 

I am sorry for the late reply.
I have rebuilt and restarted the site now.
Please check it again.

**Comment by unverbraucht** [comment]
@cybergarage I'm afraid it's offline again :(

**Comment by liulei9385** [comment]
@unverbraucht thans very much.

**Comment by cybergarage** [comment]
@ReeganExE I have moved the Maven repository from my personal site to Maven central repository last week. I am sorry to be late.

**Comment by ReeganExE** [comment]
Thanks.
