### ISSUE TITLE
Any new version？

### ISSUE THREAD

**Issue by jyuanli** [cybergarage/cybergarage-upnp#32]
two years have passed since the last release, is there a new version?
Looking forward to new release

**Comment by cybergarage** [comment]
@jyuanli　I will work to build the latest package this weekend. Thanks for your suggestion.

**Comment by jyuanli** [comment]
waiting for your new release. 
Thanks.

**Comment by jyuanli** [comment]
it has been three weeks, and still looking fowrward to your update. 

Thanks for your contributions

**Comment by cybergarage** [comment]
@jyuanli I have released the new version as v2.1.5 last week. The packages are compiled using Java 11 and all repositories and documents were moved from my personal site to public sites such as Maven central repository and GitHub pages. I am sorry to be late.
